-- Add new notification types to enum
ALTER TYPE "public"."NotificationType" ADD VALUE IF NOT EXISTS 'HANGOUT_VOTE_NEEDED';
ALTER TYPE "public"."NotificationType" ADD VALUE IF NOT EXISTS 'HANGOUT_RSVP_NEEDED';
ALTER TYPE "public"."NotificationType" ADD VALUE IF NOT EXISTS 'HANGOUT_MANDATORY_RSVP';
ALTER TYPE "public"."NotificationType" ADD VALUE IF NOT EXISTS 'HANGOUT_NEW_MESSAGE';
ALTER TYPE "public"."NotificationType" ADD VALUE IF NOT EXISTS 'HANGOUT_NEW_PHOTO';
ALTER TYPE "public"."NotificationType" ADD VALUE IF NOT EXISTS 'HANGOUT_NEW_COMMENT';
ALTER TYPE "public"."NotificationType" ADD VALUE IF NOT EXISTS 'HANGOUT_POLL_CLOSING_SOON';

